// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUP_lRPypNigIYU9EH0UghxgZdniMzBE',
    appId: '1:457461415783:web:70928db4704f010acb39c2',
    messagingSenderId: '457461415783',
    projectId: 'mjengohubapp',
    authDomain: 'mjengohubapp.firebaseapp.com',
    storageBucket: 'mjengohubapp.firebasestorage.app',
    measurementId: 'G-1HHG6TGGJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhqr-K_B3Sj2WH2wgMzYv3pS-QPRSBAw',
    appId: '1:457461415783:android:3c3edc29073d836bcb39c2',
    messagingSenderId: '457461415783',
    projectId: 'mjengohubapp',
    storageBucket: 'mjengohubapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3S175DIUB_2i3nwQcaYq28sl0ZBTQ88',
    appId: '1:457461415783:ios:5519f54c4a4ec3b8cb39c2',
    messagingSenderId: '457461415783',
    projectId: 'mjengohubapp',
    storageBucket: 'mjengohubapp.firebasestorage.app',
    iosClientId: '457461415783-ohtbhp98btr9gq6i8qnvn681bvksm5nt.apps.googleusercontent.com',
    iosBundleId: 'ke.co.mjengohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3S175DIUB_2i3nwQcaYq28sl0ZBTQ88',
    appId: '1:457461415783:ios:d2c4eb16fd9edcd4cb39c2',
    messagingSenderId: '457461415783',
    projectId: 'mjengohubapp',
    storageBucket: 'mjengohubapp.firebasestorage.app',
    iosClientId: '457461415783-h5odp86jee2tqvcjkfkcpkj7dql9r8ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.mjengoHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUP_lRPypNigIYU9EH0UghxgZdniMzBE',
    appId: '1:457461415783:web:158c0e5a73691f60cb39c2',
    messagingSenderId: '457461415783',
    projectId: 'mjengohubapp',
    authDomain: 'mjengohubapp.firebaseapp.com',
    storageBucket: 'mjengohubapp.firebasestorage.app',
    measurementId: 'G-8FQDYKTSV2',
  );
}
